# Generated by Django 5.2.11 on 2026-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
