# Generated by Django 5.2.11 on 2026-02-24 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('risk', 'Risk Confirmed'), ('active', 'Still Active'), ('resolved_locally', 'Resolved Locally'), ('observed', 'Observed This')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Engagement',
                'verbose_name_plural': 'Complaint Engagements',
                'unique_together': {('complaint', 'user', 'engagement_type')},
            },
        ),
    ]
